/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simuladorarquivo;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;




/**
 *
 * @author Jack
 */
public class Main extends javax.swing.JFrame {

    Diretorio diretorio;
    DefaultListModel<String> lista;
    int arquivoSeleciona = -1;
    /**
     * Creates new form Main
     */
    public Main() {
        diretorio = new Diretorio();
        lista = new DefaultListModel<>();

        initComponents();
        
        
        
        /* JScrollPane scroller = new JScrollPane();
        scroller.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS); */
        // lblContudoHD.
        // .getContentPane().add(scrollPane);
        // lblContudoHD, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED
        // scroller.setAlignmentY((float) 200.0);

        listArquivos.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                arquivoSeleciona = listArquivos.getSelectedIndex();
                System.out.println("arquivoSeleciona: " + arquivoSeleciona);
                lblNomeArquivo.setText(diretorio.getInodes(arquivoSeleciona).getNome());
                inConteudoArquivo.setText(diretorio.readArquvo(arquivoSeleciona));

                inodesDisplay.setText(diretorio.drawInode(arquivoSeleciona));
                lblDataCriacao.setText(diretorio.getInodes(arquivoSeleciona).getData_criacao(true));
                lblDataModificacao.setText(diretorio.getInodes(arquivoSeleciona).getData_modificacao(true));
                /* System.out.println("Mouse click.");
                int index = listArquivos.getSelectedIndex();
                System.out.println("Index Selected: " + index);
                String s = (String) listArquivos.getSelectedValue();
                System.out.println("Value Selected: " + s.toString()); */
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroHD = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listArquivos = new javax.swing.JList<>();
        lblNomeArquivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        salvarArquivo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        inConteudoArquivo = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        novoArquivo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnFormatar = new javax.swing.JButton();
        btnIncluirHD = new javax.swing.JButton();
        inTamanho = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inDivisorBloco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        excluirArquivo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        inodesDisplay = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblDataCriacao = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblDataModificacao = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblHdDisponivel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lblContudoHD = new javax.swing.JLabel();

        jButton1.setText("Operar HD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroHDLayout = new javax.swing.GroupLayout(cadastroHD.getContentPane());
        cadastroHD.getContentPane().setLayout(cadastroHDLayout);
        cadastroHDLayout.setHorizontalGroup(
            cadastroHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
            .addGroup(cadastroHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cadastroHDLayout.createSequentialGroup()
                    .addGap(297, 297, 297)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addGap(297, 297, 297)))
        );
        cadastroHDLayout.setVerticalGroup(
            cadastroHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(cadastroHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cadastroHDLayout.createSequentialGroup()
                    .addGap(213, 213, 213)
                    .addComponent(jButton1)
                    .addContainerGap(214, Short.MAX_VALUE)))
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Sistema de Arquivos");

        listArquivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listArquivosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listArquivos);

        jLabel2.setText("Nome Arquivo: ");

        salvarArquivo.setText("Salvar Arquivo");
        salvarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarArquivoActionPerformed(evt);
            }
        });

        inConteudoArquivo.setColumns(20);
        inConteudoArquivo.setRows(5);
        jScrollPane3.setViewportView(inConteudoArquivo);

        jLabel6.setText("Conteudo Arquivo: ");

        novoArquivo.setText("Novo");
        novoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoArquivoActionPerformed(evt);
            }
        });

        jLabel7.setText("Lista de Arquivos");

        btnFormatar.setText("Formatar");
        btnFormatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormatarActionPerformed(evt);
            }
        });

        btnIncluirHD.setText("Incluir");
        btnIncluirHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirHDActionPerformed(evt);
            }
        });

        inTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inTamanhoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setText("Incluir ou Alterar HD");

        jLabel3.setText("Tamanho");

        jLabel4.setText("Divisor de Bloco");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("HD");

        excluirArquivo.setText("Excluir");
        excluirArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirArquivoActionPerformed(evt);
            }
        });

        jLabel9.setText("Inodes");

        inodesDisplay.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel10.setText("Data Criação");

        jLabel11.setText("Data Modificação");

        jLabel12.setText("Armazenamento Disponível");

        lblContudoHD.setBackground(new java.awt.Color(0, 102, 102));
        lblContudoHD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContudoHD.setToolTipText("");
        lblContudoHD.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblContudoHD.setAutoscrolls(true);
        jScrollPane4.setViewportView(lblContudoHD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(lblNomeArquivo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salvarArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(novoArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel7)
                    .addComponent(excluirArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(inodesDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataCriacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDataModificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(inDivisorBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnFormatar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnIncluirHD, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHdDisponivel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 101, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salvarArquivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(novoArquivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(excluirArquivo))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inodesDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataModificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inDivisorBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFormatar)
                            .addComponent(btnIncluirHD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHdDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(diretorio.getHd() != null){
            inTamanho.setText(Integer.toString(diretorio.getHd().getTamanhoHD()));
            inDivisorBloco.setText(Integer.toString(diretorio.getHd().getNum_bloco()));
        }
        cadastroHD.setSize(757, 450); // << not working!!!
        cadastroHD.pack(); // give a suitable size to window automatically
        cadastroHD.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inTamanhoActionPerformed

    private void btnIncluirHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirHDActionPerformed
        if("".equals(inDivisorBloco.getText()) || "".equals(inTamanho.getText())){
            showMessageDialog(null, "Preencha todos os campos!");
            return;
        }
        HD hd = new HD();
        String msm = hd.criarHD(Integer.parseInt(inTamanho.getText()), Integer.parseInt(inDivisorBloco.getText()));
        if(!"OK".equals(msm)){
            showMessageDialog(null, msm);
        } else {
            showMessageDialog(null, "HD criado com sucesso!");
            diretorio.setHd(hd);
            lblContudoHD.setText(diretorio.getHd().drawConteudo());
            lblHdDisponivel.setText(Integer.toString(diretorio.getHd().tamanhoDisponivel()));
        }
    }//GEN-LAST:event_btnIncluirHDActionPerformed

    private void btnFormatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormatarActionPerformed
        // btnFormatar
        diretorio.getHd().formatarHD(); // limpa os espaços do disco
        for (int i = 0; i < diretorio.getInodes().size(); i++) 
            diretorio.apagarArquivo(i); // limpa os arquivos
        lblContudoHD.setText(diretorio.getHd().drawConteudo());
        lblHdDisponivel.setText(Integer.toString(diretorio.getHd().tamanhoDisponivel()));
    }//GEN-LAST:event_btnFormatarActionPerformed

    private void listArquivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listArquivosMouseClicked
        // showMessageDialog(null, "Clicou na lista!");
        /* String value = (String)listArquivos.getModel().getElementAt(listArquivos.locationToIndex(evt.getPoint()));
        showMessageDialog(null, value); */
    }//GEN-LAST:event_listArquivosMouseClicked

    private void salvarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarArquivoActionPerformed
        String nome = lblNomeArquivo.getText();
        String conteudo = inConteudoArquivo.getText();
        if(nome.equals("")){
            showMessageDialog(null, "Informe o nome do arquivo!");
            return;
        }
        if(arquivoSeleciona == -1){
            diretorio.criarArquivo(nome, conteudo);
            lista.addElement(nome);
            listArquivos.setModel(lista);
        } else {
            diretorio.getInodes(arquivoSeleciona).setNome(nome);
            diretorio.editarArquivo(arquivoSeleciona, conteudo);
            lista.setElementAt(nome, arquivoSeleciona);
            listArquivos.setModel(lista);
        }
        lblContudoHD.setText(diretorio.getHd().drawConteudo());
        lblHdDisponivel.setText(Integer.toString(diretorio.getHd().tamanhoDisponivel()));
        System.out.println(diretorio.getHd());
        arquivoSeleciona = -1;
        lblNomeArquivo.setText("");
        inConteudoArquivo.setText("");
        inodesDisplay.setText("");
        lblDataCriacao.setText("");
        lblDataModificacao.setText("");
    }//GEN-LAST:event_salvarArquivoActionPerformed

    private void novoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoArquivoActionPerformed
        arquivoSeleciona = -1;
        lblNomeArquivo.setText("");
        inConteudoArquivo.setText("");
        inodesDisplay.setText("");
        lblDataCriacao.setText("");
        lblDataModificacao.setText("");
    }//GEN-LAST:event_novoArquivoActionPerformed

    private void excluirArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirArquivoActionPerformed
        if(arquivoSeleciona == -1){
            showMessageDialog(null, "Nenhum arquivo selecionado!");
            return;
        }
        diretorio.apagarArquivo(arquivoSeleciona, true);
        lista.remove(arquivoSeleciona);
        listArquivos.setModel(lista);
        arquivoSeleciona = -1;
        lblNomeArquivo.setText("");
        inConteudoArquivo.setText("");
        lblContudoHD.setText(diretorio.getHd().drawConteudo());
        lblHdDisponivel.setText(Integer.toString(diretorio.getHd().tamanhoDisponivel()));
        inodesDisplay.setText("");
        lblDataCriacao.setText("");
        lblDataModificacao.setText("");
    }//GEN-LAST:event_excluirArquivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormatar;
    private javax.swing.JButton btnIncluirHD;
    private javax.swing.JFrame cadastroHD;
    private javax.swing.JButton excluirArquivo;
    private javax.swing.JTextArea inConteudoArquivo;
    private javax.swing.JTextField inDivisorBloco;
    private javax.swing.JTextField inTamanho;
    private javax.swing.JLabel inodesDisplay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblContudoHD;
    private javax.swing.JLabel lblDataCriacao;
    private javax.swing.JLabel lblDataModificacao;
    private javax.swing.JLabel lblHdDisponivel;
    private javax.swing.JTextField lblNomeArquivo;
    private javax.swing.JList<String> listArquivos;
    private javax.swing.JButton novoArquivo;
    private javax.swing.JButton salvarArquivo;
    // End of variables declaration//GEN-END:variables
}
